function onCreate()
    makeLuaSprite('bg_de_fundo','bg_de_fundo',1550,0)
    scaleObject('bg_de_fundo', 0.5,0.5)
    addLuaSprite('bg_de_fundo')
    makeLuaSprite('balcao','balcao',1550,0)
    scaleObject('balcao', 0.5,0.5)
    addLuaSprite('balcao')
    makeAnimatedLuaSprite('GF_LIGHTWUZ','GF_LIGHTWUZ',3150,185)
    addAnimationByPrefix('GF_LIGHTWUZ','GF_LIGHTWUZ','GF Dancing Beat',24,true)
    addLuaSprite('GF_LIGHTWUZ',false)
    makeAnimatedLuaSprite('toony','toony',2900,375)
    addAnimationByPrefix('toony','toony','Toony',24,true)
    scaleObject('toony', 0.8,0.8)
    makeAnimatedLuaSprite('toony_e_anjo','toony_e_anjo',2650,500)
    addAnimationByPrefix('toony_e_anjo','toony_e_anjo','Anjo flamengo idle',24,true)
    scaleObject('toony_e_anjo', 0.8,0.8)
    addLuaSprite('toony_e_anjo',false)
    addLuaSprite('toony',false)
    makeLuaSprite('cadeira','cadeira',1650,75)
    scaleObject('cadeira', 0.5,0.5)
    setScrollFactor('cadeira',1.05,0.75)
    addLuaSprite('cadeira',true)

    close(true)
end